# Deep sleep after 30 minutes of inactivity
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Uncomment the following line to increase the keyboard's wireless range
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Increase debouncing to prevent multiple inputs from switch bounce/chatter
# Slightly higher values improve stability on bouncy switches without feeling laggy
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7

# Uncomment the following line to enable USB Logging (this increases power usage by a significant amount, turn it off when not in use)
# CONFIG_ZMK_USB_LOGGING=y

# Enable Mouse Emulation
CONFIG_ZMK_MOUSE=y
